[package]
name = "compression_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iterate-text = "0.0.1"

[lib]
name = "huff"
path = "src/huff_utils.rs"
